site_name: Budget Analysis
theme: 
    name: readthedocs
    highlightjs: true
    analytics:
        gtag: G-ABC123

pages:
 - Home: index.md
 - 01 Global: 01_global.md
 - 02 Cloud regime: 02_cloud_regime.md

markdown_extensions:
  - tables
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
